### ISSUE TITLE
[회원가입] 기존 가입한 계저으로 회원가입 시도해서, 실패해도 정상적으로 회원가입한 것처럼 보임

### ISSUE THREAD

**Issue by reeny404** [reeny404/indie-n-bob#32]
![image](https://github.com/reeny404/indie-n-bob/assets/61840162/97c02588-5ff6-4b0c-9809-940963dd2cec)

**Comment by ejunyang** [comment]
해당 사항 수정 완료했습니다!

**Comment by ejunyang** [comment]
아니오.. 아직 못했습니다..
